# Application
spring.application.name=apnacarbooking

# ===============================
# Server Configuration
# ===============================
server.address=127.0.0.1
server.port=8081
server.forward-headers-strategy=framework

# ===============================
# Database Configuration (MySQL)
# ===============================
spring.datasource.url=  url
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.max-file-size=10MB

# ===============================
# Session Configuration
# ===============================
server.servlet.session.timeout=20m

# ===============================
# Email Configuration
# ===============================
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your_email@example.com
spring.mail.password=your_email_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true