# ===============================
# Application
# ===============================
spring.application.name=apnacarbooking

# ===============================
# Server Configuration
# ===============================
server.port=${PORT:8080}
server.forward-headers-strategy=framework



# ===============================
# Database Configuration (PlanetScale)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.max-file-size=10MB

# ===============================
# Session Configuration
# ===============================
server.servlet.session.timeout=20m

# ===============================
# Email Configuration
# ===============================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true